### ISSUE TITLE
cannot execute

### ISSUE THREAD

**Issue by kewuuuu** [1595258509/fuck-WZU-SPOC#3]
双击run-user.bat后出现黑窗闪退，运行python run.py --webdriver_manager --headless时报错
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from auto_answer import AutoAnswer
  File "E:\file\学习\WZU-SPOC-tools-master\WZU-SPOC-tools-master\auto_answer.py", line 3, in <module>
    from post_process import PostProcess
  File "E:\file\学习\WZU-SPOC-tools-master\WZU-SPOC-tools-master\post_process.py", line 8, in <module>
    class PostProcess(WebProcess):
  File "E:\file\学习\WZU-SPOC-tools-master\WZU-SPOC-tools-master\post_process.py", line 73, in PostProcess
    def set_submit_data(self, quiz_submissions_list: list[str]):
TypeError: 'type' object is not subscriptable

**Comment by Murlors** [comment]
Python版本太低了，typing模块在Python3.9后被直接引入，详情可见[PEP 593 – Flexible function and variable annotations](https://peps.python.org/pep-0593/)
